name: Build and Deploy
on:
  push:
    branches:
      - main 
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Building and deploying app to gh-pages
      uses: AhsanAyaz/angular-deploy-gh-pages-actions@[12.0.1] 
      with:
        github_access_token: ${{ secrets.ACCESS_TOKEN }} 
        build_configuration: production 
        base_href: https://thoughtlessmind.github.io/watchflix
        deploy_branch: gh-pages
        angular_dist_build_folder: dist/my-project
